"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "Ida"
DATA_FILES = [('', ['img'])]
PKGS = ['selenium', 'tkinter', 'platform', 'threading', 'json', 'setuptools', 'webdriver_manager', 'PIL',
        'trio', 'urllib3', 'requests', 'certifi', 'components', 'constants', 'modules']

OPTIONS = {
    'iconfile': './img/ikona.icns',
    'packages': PKGS,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "UI Testing",
        'CFBundleIdentifier': "si.nb3.ida",
        'CFBundleVersion': "1.1.1",
        'CFBundleShortVersionString': "1.1",
        'NSHumanReadableCopyright': "Copyright © 2022, Uros Dolzan, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)